### PR TITLE
Resolve Pygi keyring warning if present.

### PR DESCRIPTION
**Pull request by dbolackrs**

### CODE REVIEW

**Comment by major** [comment]
I like this idea, but it reduced the test coverage and that threw an error. Would you be able to write tests for this?

**Comment by dbolackrs** [comment]
Sorry Major. I'm a hack on my good days and every attempt to read documents for the various python testing rigs makes me wanna go back to K&R C, both barrels loaded.

If you can find some instructions not written in Pythonic English, I might be able to try.

**Comment by gtmanfred** [comment]
https://github.com/dbolackrs/supernova/pull/1 this should fix the errors with tests, but it is hacky import magic.

**Comment by major** [comment]
Wow, folks. Very nice work on this. ;)

**Pull request merged**
