### PR TITLE
Add a default `all` group

### PR DESCRIPTION
**Pull request by msabramo**
that contains all environments

so you can do stuff like:

    supernova all list

without having to add `SUPERNOVA_GROUP` settings to your config file.

Cc: @major, @sudarkoff

### CODE REVIEW

**Comment by major** [comment]
Looks like there's a merge conflict on this one.

**Comment by msabramo** [comment]
Rebased on latest `master` and fixed merge conflict.

**Comment by msabramo** [comment]
Another merge conflict. I'll fix.

**Comment by msabramo** [comment]
Fixed the merge conflict. I think this is ready for merge.

**Comment by msabramo** [comment]
Tests are passing. Phew!

**Comment by major** [comment]
Thanks for the updates!

**Pull request merged**
