### PR TITLE
Added short list command param:

### PR DESCRIPTION
**Pull request by roaet**
Command-line args:
-s, --shortlist        List all configured environments in shorter format

Example:

```
supernova --shortlist

region1 (nova) @ https://region1.mycloud.com/v2.0/
region2 (nova) @ https://region2.mycloud.com/v2.0/
region3 (nova) @ https://region3.mycloud.com/v2.0/

```

### CODE REVIEW

**Comment by roaet** [comment]
Colors are questionable. I'd like a green/darkgreen.

**Comment by major** [comment]
I like the idea -- could you check out the tests to see why they're failing?

**Comment by roaet** [comment]
Totes

**Comment by major** [comment]
Disregard that test failure -- pip failed to download something. All other tox envs look fine.

**Pull request merged**
