### PR TITLE
Implemented config directory support

### PR DESCRIPTION
**Pull request by rtrox**
Especially in the case of Rackers, many of us have an extremely large number of environments for supernova. This pull request implements an extra function (```get_config_dir()```) which attempts to pull from ~/.config/supernova.d/ or ~/.supernova.d/.

If it finds either directory, it will append each regular file the directory contains to the configObj. Currently, it allows for a config file, a config directory, or both.

### CODE REVIEW

**Comment by major** [comment]
I like where you're going with this, but some tests have failed. Could you look over the report from Travis CI above?

**Comment by swyytch** [comment]
Hey Major,

Thanks for the feedback! I have to confess this is my first time working with Travis and unit tests, but it looks like I finally have full test coverage, and 100% pass.

Is there anything else you need from me prior to merging?

Thanks!

Russell

**Comment by major** [comment]
Thanks for that, @swyytch.  I'll get a look at this later today.

**Comment by major** [comment]
I hate to do this to you @swyytch, but I merged #76 and now yours has a conflict.  I couldn't figure out a way to merge both without some code edits.

Would you have a chance to rebase your commits on top of the current master branch?  You did a great job fixing the tests!

**Comment by swyytch** [comment]
Hey @major ,

Thanks for the feedback! rebasing was a new experience for me as well, but I think I finally got it sorted out. Would you mind taking a look and letting me know what you think?

Thanks!

Russell

**Comment by major** [comment]
Sorry for the long delay, @swyytch.  If you look at the "Files changed" tab, you'll see that your branch reverts some things from the .spec and removes a bunch of blank lines from some files.  Is there any way you can remove some of those changes so we can merge this cleanly?

**Comment by msabramo** [comment]
I think that this PR can be closed in favor of #121.

**Pull request closed without merging**
